# Generated by Django 4.2 on 2023-06-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_upload',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
