# Generated by Django 4.2 on 2023-06-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization_api', '0002_alter_pdf_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_upload',
            name='name',
            field=models.CharField(default='unnamed', max_length=255),
        ),
    ]
